import { describe, it, expect } from 'vitest';
import { parse as parseYaml } from 'yaml';
import { generatePortGuardianYaml } from '../src/cli.js';
import type { PortSource } from '../src/types.js';

describe('generatePortGuardianYaml', () => {
  it('should generate valid YAML with ports', () => {
    const sources: PortSource[] = [
      { port: 3000, name: 'API Server', source: 'docker-compose.yml', confidence: 95 },
      { port: 4200, name: 'Frontend', source: 'angular.json', confidence: 90 },
    ];

    const yaml = generatePortGuardianYaml(sources);
    const parsed = parseYaml(yaml);

    expect(parsed.ports).toHaveLength(2);
    expect(parsed.ports[0]).toEqual({ port: 3000, name: 'API Server' });
    expect(parsed.ports[1]).toEqual({ port: 4200, name: 'Frontend' });
  });

  it('should handle ports without names', () => {
    const sources: PortSource[] = [
      { port: 8080, source: 'Dockerfile', confidence: 70 },
    ];

    const yaml = generatePortGuardianYaml(sources);
    const parsed = parseYaml(yaml);

    expect(parsed.ports).toHaveLength(1);
    expect(parsed.ports[0]).toEqual({ port: 8080 });
  });

  it('should quote names with YAML special characters', () => {
    const sources: PortSource[] = [
      { port: 3000, name: 'key: value', source: '.env', confidence: 80 },
      { port: 4000, name: 'has # hash', source: '.env', confidence: 80 },
    ];

    const yaml = generatePortGuardianYaml(sources);
    const parsed = parseYaml(yaml);

    expect(parsed.ports[0].name).toBe('key: value');
    expect(parsed.ports[1].name).toBe('has # hash');
  });

  it('should include header comments', () => {
    const sources: PortSource[] = [
      { port: 3000, name: 'App', source: 'test', confidence: 100 },
    ];

    const yaml = generatePortGuardianYaml(sources);

    expect(yaml).toContain('# Port Guardian Configuration');
    expect(yaml).toContain('# Generated by: port-guardian init');
  });

  it('should produce parseable YAML for all common name patterns', () => {
    const sources: PortSource[] = [
      { port: 3000, name: 'Vite (default)', source: 'vite.config.ts', confidence: 50 },
      { port: 4200, name: 'Angular (default)', source: 'angular.json', confidence: 50 },
      { port: 5432, name: 'Db Port', source: '.env', confidence: 80 },
      { port: 6379, name: 'Redis Port', source: '.env', confidence: 80 },
      { port: 8080, name: 'dev', source: 'package.json scripts', confidence: 70 },
    ];

    const yaml = generatePortGuardianYaml(sources);
    const parsed = parseYaml(yaml);

    expect(parsed.ports).toHaveLength(5);
    expect(parsed.ports.map((p: { port: number }) => p.port)).toEqual([3000, 4200, 5432, 6379, 8080]);
  });
});
