/**
 * CLI Init Command - Generate .portguardian.yml from detected ports
 */

import { writeFile, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { detectPorts } from './detector.js';
import { printDetectedPorts, printSuccess, printInfo } from './ui.js';
import type { PortSource } from './types.js';

/**
 * Init command - generate .portguardian.yml from detected ports
 */
export async function initCommand(force: boolean, ci: boolean): Promise<void> {
  const configPath = join(process.cwd(), '.portguardian.yml');
  const interactive = !force && !ci;

  // Lazy-load confirm prompt once for interactive mode
  const confirm = interactive
    ? (await import('@inquirer/prompts')).confirm
    : undefined;

  // Check if config already exists
  const configExists = await stat(configPath).then(() => true, () => false);
  if (configExists && confirm) {
    const overwrite = await confirm({
      message: '.portguardian.yml already exists. Overwrite?',
      default: false,
    });
    if (!overwrite) {
      printInfo('Aborted');
      return;
    }
  }

  // Detect ports (exclude .portguardian.yml to avoid circular detection)
  const sources = await detectPorts({ exclude: ['.portguardian.yml'] });

  if (sources.length === 0) {
    printInfo('No ports detected from project files.');
    printInfo('Creating empty config. Add ports manually.');
    const yaml = '# Port Guardian Configuration\n# See: https://github.com/ki11e6/port-guardian\nports: []\n';
    await writeFile(configPath, yaml);
    printSuccess('Created .portguardian.yml');
    return;
  }

  // Show detected ports
  printDetectedPorts(sources);

  // Confirm before writing
  if (confirm) {
    const confirmed = await confirm({
      message: `Write ${sources.length} port(s) to .portguardian.yml?`,
      default: true,
    });
    if (!confirmed) {
      printInfo('Aborted');
      return;
    }
  }

  const yamlContent = generatePortGuardianYaml(sources);
  await writeFile(configPath, yamlContent);
  printSuccess(`Created .portguardian.yml with ${sources.length} port(s)`);
}

/**
 * Generate .portguardian.yml content from detected ports
 */
export function generatePortGuardianYaml(sources: PortSource[]): string {
  let yaml = '# Port Guardian Configuration\n';
  yaml += '# Generated by: port-guardian init\n';
  yaml += '# See: https://github.com/ki11e6/port-guardian\n\n';
  yaml += 'ports:\n';

  for (const source of sources) {
    yaml += `  - port: ${source.port}\n`;
    if (source.name) {
      // Quote names with YAML-special characters
      const needsQuoting = /[:#\[\]{}&*?|>!%@`"']/.test(source.name) || source.name.trim() !== source.name;
      yaml += `    name: ${needsQuoting ? `"${source.name.replace(/"/g, '\\"')}"` : source.name}\n`;
    }
  }

  return yaml;
}
